// build.rs — 编译时将 assets/language/en_us/runtime/*.json 内嵌为 Rust 静态数据
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
  let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
  let en_us = Path::new(&manifest).join("assets/language/en_us/runtime");
  let out = Path::new(&env::var("OUT_DIR").unwrap()).join("embedded_en_us.rs");

  let mut ns_data: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();

  if en_us.is_dir() {
    if let Ok(entries) = fs::read_dir(&en_us) {
      for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "json") {
          let ns = path.file_stem().unwrap().to_string_lossy().to_string();
          if let Ok(content) = fs::read_to_string(&path) {
            if let Ok(map) = serde_json::from_str::<BTreeMap<String, String>>(&content) {
              ns_data.insert(ns, map);
            }
          }
        }
      }
    }
  }

  // 生成 Rust 代码
  let mut code = String::from(
    "// AUTO-GENERATED by build.rs — DO NOT EDIT\n\n\
         pub fn fill_namespace(ns: &str, map: &mut HashMap<String, String>) -> bool {\n",
  );

  for (ns, texts) in &ns_data {
    code.push_str(&format!("    if ns == {:?} {{\n", ns));
    for (key, val) in texts {
      code.push_str(&format!(
        "        map.insert({:?}.to_string(), {:?}.to_string());\n",
        key, val
      ));
    }
    code.push_str("        return true;\n");
    code.push_str("    }\n");
  }

  code.push_str("    false\n}\n");

  fs::write(&out, code).unwrap();
  println!("cargo:rerun-if-changed=assets/language/en_us/runtime");
}
