use crossterm::event::KeyCode;
use super::PhysicalKey;

pub fn physical_key_from_crossterm(code: KeyCode) -> Option<PhysicalKey> {
  match code {
    KeyCode::Esc => Some(PhysicalKey::Escape),
    KeyCode::Enter => Some(PhysicalKey::Enter),
    KeyCode::Tab | KeyCode::BackTab => Some(PhysicalKey::Tab),
    KeyCode::Backspace => Some(PhysicalKey::Backspace),
    KeyCode::Up => Some(PhysicalKey::ArrowUp),
    KeyCode::Down => Some(PhysicalKey::ArrowDown),
    KeyCode::Left => Some(PhysicalKey::ArrowLeft),
    KeyCode::Right => Some(PhysicalKey::ArrowRight),
    KeyCode::Home => Some(PhysicalKey::Home),
    KeyCode::End => Some(PhysicalKey::End),
    KeyCode::PageUp => Some(PhysicalKey::PageUp),
    KeyCode::PageDown => Some(PhysicalKey::PageDown),
    KeyCode::Delete => Some(PhysicalKey::Delete),
    KeyCode::Insert => Some(PhysicalKey::Insert),
    KeyCode::F(index) => Some(PhysicalKey::F(index)),
    KeyCode::Char(' ') => Some(PhysicalKey::Space),
    KeyCode::Char(ch) => physical_key_from_char(ch),
    _ => None,
  }
}

fn physical_key_from_char(ch: char) -> Option<PhysicalKey> {
  match ch.to_ascii_lowercase() {
    '0' => Some(PhysicalKey::Digit0),
    '1' => Some(PhysicalKey::Digit1),
    '2' => Some(PhysicalKey::Digit2),
    '3' => Some(PhysicalKey::Digit3),
    '4' => Some(PhysicalKey::Digit4),
    '5' => Some(PhysicalKey::Digit5),
    '6' => Some(PhysicalKey::Digit6),
    '7' => Some(PhysicalKey::Digit7),
    '8' => Some(PhysicalKey::Digit8),
    '9' => Some(PhysicalKey::Digit9),
    'a' => Some(PhysicalKey::KeyA),
    'b' => Some(PhysicalKey::KeyB),
    'c' => Some(PhysicalKey::KeyC),
    'd' => Some(PhysicalKey::KeyD),
    'e' => Some(PhysicalKey::KeyE),
    'f' => Some(PhysicalKey::KeyF),
    'g' => Some(PhysicalKey::KeyG),
    'h' => Some(PhysicalKey::KeyH),
    'i' => Some(PhysicalKey::KeyI),
    'j' => Some(PhysicalKey::KeyJ),
    'k' => Some(PhysicalKey::KeyK),
    'l' => Some(PhysicalKey::KeyL),
    'm' => Some(PhysicalKey::KeyM),
    'n' => Some(PhysicalKey::KeyN),
    'o' => Some(PhysicalKey::KeyO),
    'p' => Some(PhysicalKey::KeyP),
    'q' => Some(PhysicalKey::KeyQ),
    'r' => Some(PhysicalKey::KeyR),
    's' => Some(PhysicalKey::KeyS),
    't' => Some(PhysicalKey::KeyT),
    'u' => Some(PhysicalKey::KeyU),
    'v' => Some(PhysicalKey::KeyV),
    'w' => Some(PhysicalKey::KeyW),
    'x' => Some(PhysicalKey::KeyX),
    'y' => Some(PhysicalKey::KeyY),
    'z' => Some(PhysicalKey::KeyZ),
    _ => None,
  }
}
